#!/bin/sh
set -eu

realip_conf="${LITEWAF_REAL_IP_CONF:-/usr/local/openresty/nginx/conf/litewaf-realip.conf}"
listener_dir="${LITEWAF_LISTENER_DIR:-/etc/litewaf/listeners}"
reload_state_file="${LITEWAF_RELOAD_STATE_FILE:-/var/lib/litewaf/runtime/reload-status.json}"
runtime_uid="${LITEWAF_RUNTIME_UID:-999}"
runtime_gid="${LITEWAF_RUNTIME_GID:-999}"
trusted_cidrs="${LITEWAF_REAL_IP_TRUSTED_CIDRS:-}"
realip_header="${LITEWAF_REAL_IP_HEADER:-X-Forwarded-For}"
realip_recursive="${LITEWAF_REAL_IP_RECURSIVE:-on}"

mkdir -p "$(dirname "$realip_conf")"
mkdir -p "$listener_dir"
mkdir -p "$(dirname "$reload_state_file")"
: > "$realip_conf"
: > "$listener_dir/default.conf"
chown -R "$runtime_uid:$runtime_gid" "$listener_dir"
chmod -R u+rwX,go+rX "$listener_dir"
if [ ! -f "$reload_state_file" ]; then
  printf '{"status":"not_run","message":"reload has not run","updated_at":""}\n' > "$reload_state_file"
fi

normalized_cidrs="$(printf '%s' "$trusted_cidrs" | tr -d '[:space:],')"
if [ "$normalized_cidrs" != "" ]; then
  case "$realip_header" in
    *[!A-Za-z0-9_-]*|"")
      echo "invalid LITEWAF_REAL_IP_HEADER: $realip_header" >&2
      exit 1
      ;;
  esac

  case "$(printf '%s' "$realip_recursive" | tr '[:upper:]' '[:lower:]')" in
    1|true|yes|on)
      realip_recursive="on"
      ;;
    0|false|no|off)
      realip_recursive="off"
      ;;
    *)
      echo "invalid LITEWAF_REAL_IP_RECURSIVE: $realip_recursive" >&2
      exit 1
      ;;
  esac

  {
    echo "# generated by litewaf gateway entrypoint"
    echo "real_ip_header $realip_header;"
    echo "real_ip_recursive $realip_recursive;"
  } > "$realip_conf"

  for cidr in $(printf '%s' "$trusted_cidrs" | tr ',' ' '); do
    case "$cidr" in
      *[!0-9A-Fa-f:./]*|"")
        echo "invalid LITEWAF_REAL_IP_TRUSTED_CIDRS entry: $cidr" >&2
        exit 1
        ;;
    esac
    echo "set_real_ip_from $cidr;" >> "$realip_conf"
  done
fi

exec "$@"
