worker_processes auto;
pid /var/run/litewaf-nginx.pid;
error_log /dev/stderr warn;

events {
    worker_connections 1024;
}

http {
    access_log /dev/stdout;
    lua_package_path "/usr/local/openresty/nginx/lua/?.lua;;";
    lua_shared_dict litewaf_rate_limit 10m;
    lua_shared_dict litewaf_dynamic_ban 10m;
    lua_shared_dict litewaf_dynamic_ban_clear 1m;
    lua_shared_dict litewaf_dynamic_protection 10m;
    lua_shared_dict litewaf_metrics 10m;
    include /usr/local/openresty/nginx/conf/litewaf-realip.conf;
    include /usr/local/openresty/nginx/conf/litewaf-resolver.conf;

    init_by_lua_block {
        litewaf = require "litewaf"
    }

    init_worker_by_lua_block {
        litewaf.init_worker()
    }

    include /usr/local/openresty/nginx/conf/litewaf-admin.conf;
    include /etc/litewaf/listeners/*.conf;
}
